### ISSUE TITLE
Error with image_minifier and css_minifier

### ISSUE THREAD

**Issue by galexrt** [unhealthy/hexo-all-minifier#11]
My `_config.yml`:
```
[...]
html_minifier:
  enable: true
  exclude: []

css_minifier:
  enable: false
  exclude:
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

image_minifier:
  enable: false
  interlaced: true
  multipass: true
  optimizationLevel: 9
  pngquant: true
  progressive: true
[...]
```
My `package.json`:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-all-minifier": "0.0.13",
    "hexo-deployer-rsync": "^0.1.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.1.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-seo-friendly-sitemap": "0.0.15",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-simple-tagcloud": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-tag-googlecharts": "^1.0.2"
  }
}
```
`image_minifier` Error Output:
```
┌─[atrost@deblap01] - [~/Projects/websites/edenmal.net] - [2016-05-17 02:04:48]
└─[0] <> hexo server    
INFO  Start processing
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/ASCII-Link-Dump.md [ 1.15% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Docker-for-Admins-Workshop-Recap-Presentation.md [ 1.54% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Docker-for-Admins-Workshop.md [ 0.31% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/First-Post.md [ 1.06% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/In-search-of-a-webhosting.md [ 0.46% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Kubernetes-Presentation.md [ 2.18% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Online-Courses-Courses-everywhere.md [ 1.85% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Rant-about-Tutorials.md [ 0.13% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/SRCDS-Server-Restarter-Script.md [ 0.68% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Story-Time-No-1.md [ 0.45% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/TITLE-HERE-Story-Time-No-2.md [ 1.77% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/hello-world.md [ 0.41% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Docker-for-Admins-Workshop-v2.md [ 0.23% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/404.md [ -1.38% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/about/index.md [ 1.01% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/categories/index.html [ NaN% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/tags/index.html [ NaN% saved]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Imagemin is not a constructor
    at /home/atrost/Projects/websites/edenmal.net/node_modules/hexo-all-minifier/lib/filter.js:122:28
    at tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:628:18)
    at /home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/atrost/Projects/websites/edenmal.net/node_modules/stream-to-array/index.js:54:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
FATAL Imagemin is not a constructor
TypeError: Imagemin is not a constructor
    at /home/atrost/Projects/websites/edenmal.net/node_modules/hexo-all-minifier/lib/filter.js:122:28
    at tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:628:18)
    at /home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/atrost/Projects/websites/edenmal.net/node_modules/stream-to-array/index.js:54:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

`css_minifier` Error Output:
```
┌─[atrost@deblap01] - [~/Projects/websites/edenmal.net] - [2016-05-17 02:10:33]
└─[0] <> hexo clean; hexo server
INFO  Deleted database.
INFO  Start processing
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/ASCII-Link-Dump.md [ 1.15% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Docker-for-Admins-Workshop-Recap-Presentation.md [ 1.54% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Docker-for-Admins-Workshop.md [ 0.31% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/First-Post.md [ 1.06% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/In-search-of-a-webhosting.md [ 0.46% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Kubernetes-Presentation.md [ 2.18% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Online-Courses-Courses-everywhere.md [ 1.85% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Rant-about-Tutorials.md [ 0.13% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/SRCDS-Server-Restarter-Script.md [ 0.68% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Story-Time-No-1.md [ 0.45% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/TITLE-HERE-Story-Time-No-2.md [ 1.77% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/hello-world.md [ 0.41% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/_posts/Docker-for-Admins-Workshop-v2.md [ 0.23% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/404.md [ -1.38% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/about/index.md [ 1.01% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/categories/index.html [ NaN% saved]
INFO  update Optimize HTML: /home/atrost/Projects/websites/edenmal.net/source/tags/index.html [ NaN% saved]
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
ERROR Asset render failed: bootstrap/css/bootstrap.min.css
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at new CleanCSS (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/node_modules/clean-css/lib/clean.js:55:130)
    at Compress.compress (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/build/compress.js:34:18)
    at exports.default (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/build/compress.js:11:49)
    at Function.More.compress (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/build/More.js:430:12)
    at Hexo.OptimizeCSS (/home/atrost/Projects/websites/edenmal.net/node_modules/hexo-all-minifier/lib/filter.js:56:26)
    at Hexo.tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/method.js:15:34)
    at /home/atrost/Projects/websites/edenmal.net/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
INFO  update Optimize JS: /home/atrost/Projects/websites/edenmal.net/themes/hexadillax/source/js/jquery.backstretch.min.js [ 0.97% saved]
INFO  update Optimize JS: /home/atrost/Projects/websites/edenmal.net/themes/hexadillax/source/bootstrap/js/bootstrap.min.js [ 0.34% saved]
INFO  update Optimize JS: /home/atrost/Projects/websites/edenmal.net/themes/hexadillax/source/js/jquery-2.1.0.min.js [ 0.10% saved]
ERROR Asset render failed: css/style.css
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at new CleanCSS (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/node_modules/clean-css/lib/clean.js:55:130)
    at Compress.compress (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/build/compress.js:34:18)
    at exports.default (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/build/compress.js:11:49)
    at Function.More.compress (/home/atrost/Projects/websites/edenmal.net/node_modules/more-css/build/More.js:430:12)
    at Hexo.OptimizeCSS (/home/atrost/Projects/websites/edenmal.net/node_modules/hexo-all-minifier/lib/filter.js:56:26)
    at Hexo.tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/method.js:15:34)
    at /home/atrost/Projects/websites/edenmal.net/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/atrost/Projects/websites/edenmal.net/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
INFO  update Optimize JS: /home/atrost/Projects/websites/edenmal.net/themes/hexadillax/source/js/common.js [ 28.70% saved]
INFO  update Optimize JS: /home/atrost/Projects/websites/edenmal.net/themes/hexadillax/source/js/headroom.min.js [ 3.69% saved]
^CINFO  See you again
```

I'm getting the above error when `image_minifer` is enabled and the below error when having `css_minifier` enabled.
Disabling both `image_minifer` and `css_minifier` "removes" the errors.

For the `image_minifier` error: Do I need to install a missing dependency?
For the `css_minifier` error: Is this a problem caused by the theme I'm using? The error only occurs with `css_minifier` enabled.

**Comment by tiexo** [comment]
我也报错了..

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html          
TypeError: (input, output, opts) => {                                                                            
        if (!Array.isArray(input)) {                                                                             
                return Promise.reject(new TypeError('Expected an arr...<omitted>...                              
} is not a constructor                                                                                           
    at /home/coding/workspace/node_modules/hexo-all-minifier/lib/filter.js:122:28                                
    at tryCatcher (/home/coding/workspace/node_modules/bluebird/js/release/util.js:16:23)                        
    at Promise._settlePromiseFromHandler (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:502:
31)                                                                                                              
    at Promise._settlePromise (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:559:18)        
    at Promise._settlePromise0 (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:604:10)       
    at Promise._settlePromises (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:683:18)       
    at Promise._fulfill (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:628:18)              
    at Promise._resolveCallback (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:423:57)      
    at Promise._settlePromiseFromHandler (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:514:
17)                                                                                                              
    at Promise._settlePromise (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:559:18)        
    at Promise._settlePromise0 (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:604:10)       
    at Promise._settlePromises (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:683:18)       
    at Promise._fulfill (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:628:18)              
    at /home/coding/workspace/node_modules/bluebird/js/release/nodeback.js:42:21                                 
    at /home/coding/workspace/node_modules/stream-to-array/index.js:54:9                                         
    at _combinedTickCallback (node.js:370:9)                                                                     
    at process._tickCallback (node.js:401:11)                                                                    
FATAL (input, output, opts) => {                                                                                 
        if (!Array.isArray(input)) {                                                                             
                return Promise.reject(new TypeError('Expected an arr...<omitted>...                              
} is not a constructor                                                                                           
TypeError: (input, output, opts) => {                                                                            
        if (!Array.isArray(input)) {                                                                             
                return Promise.reject(new TypeError('Expected an arr...<omitted>...                              
} is not a constructor                                                                                           
    at /home/coding/workspace/node_modules/hexo-all-minifier/lib/filter.js:122:28                                
    at tryCatcher (/home/coding/workspace/node_modules/bluebird/js/release/util.js:16:23)                        
    at Promise._settlePromiseFromHandler (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:502:
31)                                                                                                              
    at Promise._settlePromise (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:559:18)        
    at Promise._settlePromise0 (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:604:10)       
    at Promise._settlePromises (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:683:18)       
    at Promise._fulfill (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:628:18)              
    at Promise._resolveCallback (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:423:57)      
    at Promise._settlePromiseFromHandler (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:514:
17)                                                                                                              
    at Promise._settlePromise (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:559:18)        
    at Promise._settlePromise0 (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:604:10)       
    at Promise._settlePromises (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:683:18)       
    at Promise._fulfill (/home/coding/workspace/node_modules/bluebird/js/release/promise.js:628:18)              
    at /home/coding/workspace/node_modules/bluebird/js/release/nodeback.js:42:21                                 
    at /home/coding/workspace/node_modules/stream-to-array/index.js:54:9                                         
    at _combinedTickCallback (node.js:370:9)                                                                     
    at process._tickCallback (node.js:401:11)             
```

**Comment by imruxin** [comment]
我这边也报错了，不过我只设置了html压缩。
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: (input, output, opts) => {
	if (!Array.isArray(input)) {
		return Promise.reject(new TypeError('Expected an arr...<omitted>...
} is not a constructor
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/lib/filter.js:122:28
    at tryCatcher (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/ruxin/website/blog/node_modules/stream-to-array/index.js:54:9
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
FATAL (input, output, opts) => {
	if (!Array.isArray(input)) {
		return Promise.reject(new TypeError('Expected an arr...<omitted>...
} is not a constructor
TypeError: (input, output, opts) => {
	if (!Array.isArray(input)) {
		return Promise.reject(new TypeError('Expected an arr...<omitted>...
} is not a constructor
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/lib/filter.js:122:28
    at tryCatcher (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/ruxin/website/blog/node_modules/stream-to-array/index.js:54:9
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

**Comment by tiexo** [comment]
@imruxin  我现在没用这个整合插件，分别用了三个单独的，没报错
http://www.tiexo.cn/html-css-js/

**Comment by unhealthy** [comment]
@tiexo @imruxin 你们两个的错可能跟nodejs的版本有关，你们用的是node5还是node6呢？

**Comment by imruxin** [comment]
@unhealthy 我的是`v5.0.0`

**Comment by tiexo** [comment]
@unhealthy 我是V5.7.0

**Comment by unhealthy** [comment]
@galexrt @tiexo @imruxin 
Bugs are fixed and new version has been published.
These bugs is caused by the new api of `imagemin` and `more-css`.
Please try and feel free to give me feedback if you come across any bugs.

**Comment by galexrt** [comment]
Thanks for the fix! It's working now. :)

**Comment by imruxin** [comment]
@unhealthy 刚去下载试了一下，我的问题还存在。
版本信息
```
hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 15.5.0 darwin x64
http_parser: 2.5.0
node: 5.0.0
v8: 4.6.85.28
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2d
```

在出现错误前会有两行NaN%的文字
```
...
INFO  update Optimize HTML: /Users/ruxin/website/blog/source/_posts/write-to-2012-and-four-days-later-birthday.md [ 0.99% saved]
INFO  update Optimize HTML: /Users/ruxin/website/blog/source/404.html [ 22.98% saved]
INFO  update Optimize HTML: /Users/ruxin/website/blog/source/categories/index.md [ NaN% saved]
INFO  update Optimize HTML: /Users/ruxin/website/blog/source/about/index.md [ 1.95% saved]
INFO  update Optimize HTML: /Users/ruxin/website/blog/source/tags/index.md [ NaN% saved]
```

接下去就是报错信息
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: (input, output, opts) => {
	if (!Array.isArray(input)) {
		return Promise.reject(new TypeError('Expected an arr...<omitted>...
} is not a constructor
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/lib/filter.js:122:28
    at tryCatcher (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/ruxin/website/blog/node_modules/stream-to-array/index.js:54:9
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
FATAL (input, output, opts) => {
	if (!Array.isArray(input)) {
		return Promise.reject(new TypeError('Expected an arr...<omitted>...
} is not a constructor
TypeError: (input, output, opts) => {
	if (!Array.isArray(input)) {
		return Promise.reject(new TypeError('Expected an arr...<omitted>...
} is not a constructor
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/lib/filter.js:122:28
    at tryCatcher (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/ruxin/website/blog/node_modules/hexo-all-minifier/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/ruxin/website/blog/node_modules/stream-to-array/index.js:54:9
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```
